booklist: book_ver2_main.o	book_ver2_source.o
	gcc -o booklist book_ver2_main.c book_ver2_source.c

book_ver2_source.o: book_ver2_source.c
	gcc -c book_ver2_head.h	book_ver2_source.c

book_ver2_main.o:	book_ver2_main.c
	gcc -c book_ver2_head.h book_ver2_main.c
